// Code generated by "stringer -type Widget"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ItemAdd-0]
	_ = x[ItemRemove-1]
}

const _Widget_name = "ItemAddItemRemove"

var _Widget_index = [...]uint8{0, 7, 17}

func (i Widget) String() string {
	if i < 0 || i >= Widget(len(_Widget_index)-1) {
		return "Widget(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Widget_name[_Widget_index[i]:_Widget_index[i+1]]
}
