// Code generated by "stringer -type WidgetType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Button-0]
	_ = x[Entry-1]
	_ = x[Label-2]
}

const _WidgetType_name = "ButtonEntryLabel"

var _WidgetType_index = [...]uint8{0, 6, 11, 16}

func (i WidgetType) String() string {
	if i < 0 || i >= WidgetType(len(_WidgetType_index)-1) {
		return "WidgetType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WidgetType_name[_WidgetType_index[i]:_WidgetType_index[i+1]]
}
